# Generated by Django 3.1.3 on 2020-11-25 03:21

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Reservations',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('check_in', models.TimeField(verbose_name='Time for Check In')),
                ('check_out', models.TimeField(verbose_name='Time for Check Out')),
                ('arrival_date', models.DateField(verbose_name='Date of Arrival')),
                ('departure_date', models.DateField(verbose_name='Date of Departure')),
                ('hrs_to_stay', models.PositiveIntegerField(verbose_name='Hours to Stay')),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reservation_user', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
