# Generated by Django 3.1.3 on 2020-11-27 18:09

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Room',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('room_type', models.CharField(choices=[('Standard Room', 'Standard Room'), ('Deluxe Room', 'Deluxe Room'), ('VIP Room', 'VIP Room')], max_length=100, verbose_name='Type of Room')),
                ('room_no', models.PositiveIntegerField(help_text='Should be unique and not existing room no', unique=True, verbose_name='Room No')),
                ('available', models.BooleanField(default=False, verbose_name='Available')),
            ],
        ),
        migrations.CreateModel(
            name='Reservations',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('check_in', models.TimeField(verbose_name='Time for Check In')),
                ('check_out', models.TimeField(verbose_name='Time for Check Out')),
                ('arrival_date', models.DateField(verbose_name='Date of Arrival')),
                ('departure_date', models.DateField(verbose_name='Date of Departure')),
                ('hrs_to_stay', models.PositiveIntegerField(verbose_name='Hours to Stay')),
                ('date_created', models.DateField(auto_now_add=True)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reservation_user', to=settings.AUTH_USER_MODEL)),
                ('room', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='room_type_and_no', to='reservations.room', verbose_name='Room Type & No')),
            ],
        ),
        migrations.CreateModel(
            name='CheckInAndOut',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('check_in', models.BooleanField(default=False, verbose_name='Checking In or Out?')),
                ('check_in_date_time', models.DateTimeField()),
                ('reservations', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='reservations.reservations', verbose_name="Customer's Reservations")),
            ],
        ),
    ]
