# Generated by Django 3.1.3 on 2020-11-25 03:22

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('reservations', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='reservations',
            name='date_created',
            field=models.DateField(auto_now_add=True, default=datetime.datetime(2020, 11, 25, 3, 22, 8, 157019, tzinfo=utc)),
            preserve_default=False,
        ),
    ]
