# Generated by Django 3.1.3 on 2020-11-26 08:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservations', '0002_reservations_date_created'),
    ]

    operations = [
        migrations.AddField(
            model_name='reservations',
            name='room',
            field=models.CharField(choices=[('Standard Room', 'Standard Room'), ('Deluxe Room', 'Deluxe Room'), ('VIP Room', 'VIP Room')], default=1, max_length=100, verbose_name='Type of Room'),
            preserve_default=False,
        ),
    ]
