# Generated by Django 3.1.3 on 2020-11-28 15:26

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('reservations', '0002_auto_20201128_1434'),
    ]

    operations = [
        migrations.RenameField(
            model_name='reservations',
            old_name='check_out',
            new_name='check_out_datetime',
        ),
        migrations.RemoveField(
            model_name='reservations',
            name='arrival_date',
        ),
        migrations.RemoveField(
            model_name='reservations',
            name='check_in',
        ),
        migrations.RemoveField(
            model_name='reservations',
            name='departure_date',
        ),
        migrations.AddField(
            model_name='reservations',
            name='check_in_datetime',
            field=models.DateTimeField(default=datetime.datetime(2020, 11, 28, 15, 26, 9, 141701, tzinfo=utc), verbose_name='Time for Check In'),
            preserve_default=False,
        ),
    ]
