# Generated by Django 3.1.3 on 2020-11-26 09:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservations', '0003_reservations_room'),
    ]

    operations = [
        migrations.CreateModel(
            name='Room',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('room_type', models.CharField(choices=[('Standard Room', 'Standard Room'), ('Deluxe Room', 'Deluxe Room'), ('VIP Room', 'VIP Room')], max_length=100, verbose_name='Type of Room')),
                ('room_no', models.PositiveIntegerField(verbose_name='Room No')),
            ],
        ),
    ]
