# Generated by Django 3.1.3 on 2020-11-28 15:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservations', '0003_auto_20201128_2326'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reservations',
            name='check_in_datetime',
            field=models.DateTimeField(verbose_name='Date & Time for Check In'),
        ),
        migrations.AlterField(
            model_name='reservations',
            name='check_out_datetime',
            field=models.DateTimeField(verbose_name='Date & Time for Check Out'),
        ),
    ]
