# Generated by Django 3.1.3 on 2020-11-26 10:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservations', '0004_room'),
    ]

    operations = [
        migrations.AddField(
            model_name='room',
            name='available',
            field=models.BooleanField(default=False, verbose_name='Available'),
        ),
    ]
