# Generated by Django 3.1.3 on 2020-11-28 15:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservations', '0004_auto_20201128_2350'),
    ]

    operations = [
        migrations.AddField(
            model_name='reservations',
            name='active',
            field=models.BooleanField(default=True),
        ),
    ]
