# Generated by Django 3.1.3 on 2020-11-26 13:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservations', '0006_auto_20201126_2141'),
    ]

    operations = [
        migrations.AlterField(
            model_name='room',
            name='room_no',
            field=models.PositiveIntegerField(help_text='Should be unique and not existing room no', unique=True, verbose_name='Room No'),
        ),
    ]
